src/Entity/Post.php
<?php declare(strict_types=1);

namespace App\Entity;

use App\Repository\CommentRepository;
use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $filename = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getCommentsQuantity(): int
    {
        return count($this->comments);
    }
}

src/Entity/User.php
<?php declare(strict_types=1);

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[UniqueEntity(fields: ['nickname'], message: 'There is already an account with this nickname')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $about = null;

    #[ORM\Column]
    private ?int $type = 1;

    #[ORM\Column(length: 70, nullable: true, unique: true)]
    private ?string $nickname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Post::class, orphanRemoval: true)]
    private Collection $posts;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $googleId = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $githubId = null;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(?string $about): self
    {
        $this->about = $about;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getNickname(): string|int|null
    {
        return $this->nickname ?? $this->id;
    }

    public function setNickname(?string $nickname): self
    {
        $this->nickname = $nickname;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function getFullName(): ?string
    {
        return $this->first_name . " " . $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setUserId($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUserId() === $this) {
                $post->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(?string $googleId): self
    {
        $this->googleId = $googleId;

        return $this;
    }

    public function getGithubId(): ?string
    {
        return $this->githubId;
    }

    public function setGithubId(?string $githubId): self
    {
        $this->githubId = $githubId;

        return $this;
    }
}

src/Controller/ProfileController.php
<?php declare(strict_types=1);

namespace App\Controller;

use App\Entity\Post;
use App\Entity\User;
use App\Form\UserType;
use App\Service\Like;
use App\Service\Uploaders\AvatarPictureUploader;
use App\Service\Subscription;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;

class ProfileController extends AbstractController
{
    #[Route('/profile', name: 'my_profile')]
    public function myProfile(): Response
    {
        $currentUser = $this->getUser();
        if (!$currentUser) {
            return $this->redirectToRoute('app_login');
        }

        return $this->redirectToRoute('profile', [
            'nickname' => $currentUser->getNickname()
        ]);
    }


    #[Route('/profile/{nickname}', name: 'profile')]
    public function view(int|string $nickname, ManagerRegistry $doctrine, Subscription $subscription, Like $like): Response
    {
        //Просматривать профили может только авторизированный пользователь
        $currentUser = $this->getUser();
        if (!$currentUser) {
            return $this->redirectToRoute('app_login');
        }

        $user = $doctrine->getRepository(User::class)->findOneByNickname($nickname);
        $userSubscriptionsIds = $subscription->getUserSubscriptionsIds($user);
        $userSubscriptions = $doctrine->getRepository(User::class)->findBy(['id' => $userSubscriptionsIds]);
        $userFollowersIds = $subscription->getUserFollowersIds($user);
        $userFollowers = $doctrine->getRepository(User::class)->findBy(['id' => $userFollowersIds]);
        $numberUserFollowers = $subscription->countUserFollowers($user);
        $numberUserSubscriptions = $subscription->countUserSubscriptions($user);
        $mutualSubscriptionsIds = $subscription->getMutualSubscriptionsIds($user);
        $mutualSubscriptions = $doctrine->getRepository(User::class)->findBy(['id' => $mutualSubscriptionsIds]);
        $userPosts = $doctrine->getRepository(Post::class)->findBy(['user' => $user], ['created_at'=>"DESC"]);
        $userLikes = $like->getUserLikesIds($this->getUser());

        return $this->render('profile/view.html.twig', [
            'user' => $user,
            'userSubscriptions' => $userSubscriptions,
            'userFollowers' => $userFollowers,
            'numberUserFollowers' => $numberUserFollowers,
            'numberUserSubscriptions' => $numberUserSubscriptions,
            'mutualSubscriptions' => $mutualSubscriptions,
            'currentUser' => $currentUser,
            'userPosts' => $userPosts,
            'userLikes' => $userLikes,
            'like' => $like
        ]);
    }

    #[Route('/profile/{user}/edit', name: 'edit_profile')]
    public function edit(User $user, Request $request, EntityManagerInterface $entityManager, AvatarPictureUploader $avatarUploader): Response
    {
        //Пользователь может редактировать только свой профил
        if ($this->getUser() !== $user) {
            return $this->redirectToRoute('profile', [
                'nickname' => $user->getNickname()
            ]);
        }
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $pictureFile */
            $pictureFile = $form->get('picture')->getData();
            if ($pictureFile) {
                $pictureFileName = $avatarUploader->upload($pictureFile);
                // Remove previous picture from storage
                if ($user->getPicture()) {
                    $avatarUploader->delete($user->getPicture());
                }
                $user->setPicture($pictureFileName);
            }
            $user->setUpdatedAt(new \DateTimeImmutable('now'));
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('profile', [
                'nickname' => $user->getNickname()
            ]);
        }

        return $this->render('profile/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/profile/subscribe/{user}', name: 'subscribe')]
    public function subscribe(User $user, Subscription $subscription): Response
    {
        if ($this->getUser() === $user) {
            return $this->redirectToRoute('profile', [
                'nickname' => $user->getNickname()
            ]);
        }
        $subscription->followUser($user);

        return $this->redirectToRoute('profile', [
            'nickname' => $user->getNickname()
        ]);
    }

    #[Route('/profile/unsubscribe/{user}', name: 'unsubscribe')]
    public function unsubscribe(User $user, Subscription $subscription): Response
    {
        if ($this->getUser() === $user) {
            return $this->redirectToRoute('profile', [
                'nickname' => $user->getNickname()
            ]);
        }
        $subscription->unfollowUser($user);

        return $this->redirectToRoute('profile', [
            'nickname' => $user->getNickname()
        ]);
    }
}

templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProfileController!{% endblock %}

{% block body %}
<h1>Вы на странице редактирования профиля</h1>
    {{ form_start(form) }}
    {{ form_row(form.picture) }}
    {{ form_end(form) }}
{% endblock %}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProfileController!{% endblock %}

{% block body %}
    <a href="/logout"><h1>logout</h1> </a>
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/OpenServer/domains/symfogram/src/Controller/ProfileController.php'|file_link(0) }}">src/Controller/ProfileController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/OpenServer/domains/symfogram/templates/profile/index.html.twig'|file_link(0) }}">templates/profile/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/profile/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProfileController!{% endblock %}

{% block body %}

    {% if(user.picture) %}
        <img src="{{ asset('uploads/avatar_pictures/' ~ user.picture) }}" alt="avatar picture" height="300">
    {% else %}
        <img src="{{ asset('images/default_avatar.png') }}" alt="avatar picture" height="300">
    {% endif %}
    <h1>{{ user.firstName }} {{ user.lastName }}! ✅</h1>
    <p>{{ user.about }}</p>

    {% if(currentUser is same as (user)) %}
        <a href="{{ path('edit_profile', {user:user.id}) }}">
            <button type="button" class="btn btn-primary">
                Edit profile
            </button>
        </a>

        <a href="{{ path('app_post_new') }}">
            <button type="button" class="btn btn-primary">
                New post
            </button>
        </a>
    {% endif %}

    <hr>
    {% if(currentUser is not same as (user)) %}
        <a href="{{ path('subscribe', {user:user.id}) }}">
            <button type="button" class="btn btn-primary">
                Подписаться
            </button>
        </a>
        <a href="{{ path('unsubscribe', {user:user.id}) }}">
            <button type="button" class="btn btn-primary">
                Отписаться
            </button>
        </a>
    {% endif %}
    <hr>
    <p>Friends, who a also following {{ user.firstName }} {{ user.lastName }}</p>
    <ul>
        {% for subscription in mutualSubscriptions %}
            <li><a href="{{ path('profile', {nickname:subscription.nickname}) }}">
                    {{ subscription.firstName }}
                    {{ subscription.lastName }}
                </a>
            </li>
        {% endfor %}
    </ul>

    <hr>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#subscription">
        Subscriptions: {{ numberUserSubscriptions }}
    </button>

    <!-- Modal -->
    <div class="modal fade" id="subscription" tabindex="-1" role="dialog" aria-labelledby="subscriptionTitle"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Subscriptions</h5>
                </div>
                <div class="modal-body">
                    <ul>
                        {% for subscription in userSubscriptions %}
                            <li><a href="{{ path('profile', {nickname:subscription.nickname}) }}">
                                    {{ subscription.firstName }}
                                    {{ subscription.lastName }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>


    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#followers">
        Followers: {{ numberUserFollowers }}
    </button>

    <!-- Modal -->
    <div class="modal fade" id="followers" tabindex="-1" role="dialog" aria-labelledby="followersTitle"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Followers</h5>
                </div>
                <div class="modal-body">
                    <h1>sdasdas</h1>
                    <ul>
                        {% for follower in userFollowers %}
                            <li><a href="{{ path('profile', {nickname:follower.nickname}) }}">
                                    {{ follower.firstName }}
                                    {{ follower.lastName }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>


    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Filename</th>
            <th>Description</th>
            <th>Created_at</th>
            <th>Updated_at</th>
            <th>actions</th>
            <th>Likes quantity</th>
            <th>Comments quantity</th>
            <th>Like</th>
        </tr>
        </thead>
        <tbody>
        {% for post in userPosts %}
            <tr>
                <td>{{ post.id }}</td>
                <td><img src="{{ asset('/uploads/post_pictures/' ~ post.filename) }}" alt="post picture" height="150"></td>
                <td>{{ post.description }}</td>
                <td>{{ post.createdAt ? post.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ post.updatedAt ? post.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_post_show', {'id': post.id}) }}">show</a>
                    {% if(currentUser is same as (user)) %}
                    <a href="{{ path('app_post_edit', {'id': post.id}) }}">edit</a>
                    {{ include('post/_delete_form.html.twig') }}
                    {% endif %}
                </td>
                <td>{{ like.countPostLikes(post) }}</td>
                <td><a href="{{ path('app_post_show', {'id': post.id}) }}">
                        {{ post.commentsQuantity() }} comments
                    </a>
                </td>
                <td>
                    {% if post.id not in userLikes %}
                        <a href="{{ path('app_post_like', {id:post.id}) }}" class="btn btn-primary ">
                            Like
                        </a>
                    {% else %}
                        <a href="{{ path('app_post_unlike', {id:post.id}) }}" class="btn btn-primary ">
                            Unlike
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>



{% endblock %}